package com.coderbd.pojo;
// Generated Feb 1, 2018 4:35:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private String studentName;
     private Date admissionDate;
     private Date birthDate;
     private String fatherName;
     private String mobileNo;
     private String motherName;
     private String note;
     private Integer regiNo;
     private Integer rollNo;
     private Integer sclassId;

    public Student() {
    }

    public Student(String studentName, Date admissionDate, Date birthDate, String fatherName, String mobileNo, String motherName, String note, Integer regiNo, Integer rollNo, Integer sclassId) {
       this.studentName = studentName;
       this.admissionDate = admissionDate;
       this.birthDate = birthDate;
       this.fatherName = fatherName;
       this.mobileNo = mobileNo;
       this.motherName = motherName;
       this.note = note;
       this.regiNo = regiNo;
       this.rollNo = rollNo;
       this.sclassId = sclassId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public Date getAdmissionDate() {
        return this.admissionDate;
    }
    
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Integer getRegiNo() {
        return this.regiNo;
    }
    
    public void setRegiNo(Integer regiNo) {
        this.regiNo = regiNo;
    }
    public Integer getRollNo() {
        return this.rollNo;
    }
    
    public void setRollNo(Integer rollNo) {
        this.rollNo = rollNo;
    }
    public Integer getSclassId() {
        return this.sclassId;
    }
    
    public void setSclassId(Integer sclassId) {
        this.sclassId = sclassId;
    }




}


