package com.coderbd.pojo;
// Generated Feb 1, 2018 4:35:58 PM by Hibernate Tools 4.3.1



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private int id;
     private String note;
     private String subjectCode;
     private String subjectName;
     private Integer subjectId;

    public Subject() {
    }

	
    public Subject(int id) {
        this.id = id;
    }
    public Subject(int id, String note, String subjectCode, String subjectName, Integer subjectId) {
       this.id = id;
       this.note = note;
       this.subjectCode = subjectCode;
       this.subjectName = subjectName;
       this.subjectId = subjectId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }




}


