package com.coderbd.pojo;
// Generated Feb 1, 2018 4:35:58 PM by Hibernate Tools 4.3.1



/**
 * TeacherAssignClassSub generated by hbm2java
 */
public class TeacherAssignClassSub  implements java.io.Serializable {


     private int id;

    public TeacherAssignClassSub() {
    }

    public TeacherAssignClassSub(int id) {
       this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }




}


