package com.coderbd.pojo;
// Generated Feb 1, 2018 4:35:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private int id;
     private Date birthDate;
     private Date joiningDate;
     private String mobileNo;
     private String note;
     private String teacherName;

    public Teacher() {
    }

	
    public Teacher(int id) {
        this.id = id;
    }
    public Teacher(int id, Date birthDate, Date joiningDate, String mobileNo, String note, String teacherName) {
       this.id = id;
       this.birthDate = birthDate;
       this.joiningDate = joiningDate;
       this.mobileNo = mobileNo;
       this.note = note;
       this.teacherName = teacherName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Date getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }




}


